#!/usr/bin/env python3
"""
Generate cross-verification vectors for the BuilderDepositContract Foundry tests.

Uses py_ecc as the reference implementation:
  * `depositCase()` — a deterministic deposit signature produced by
    `py_ecc.bls.G2ProofOfPossession.Sign` (the Eth2 ciphersuite), together
    with the (X, Y) affine decomposition of the resulting BLS points.
  * `depositSigningRoot()` — the canonical SSZ signing root that the
    `BuilderDepositContract._computeDepositSigningRoot` function must match.

Output: a self-contained Solidity file `test/Vectors.sol` that the Foundry
test imports as constants. No JSON parsing in Solidity needed.

Run from this directory:
    /tmp/eipenv/bin/python gen_vectors.py > test/Vectors.sol
"""

import hashlib
import sys
from py_ecc.optimized_bls12_381 import (
    G1, G2, field_modulus as Q, multiply, normalize, FQ, FQ2,
)
from py_ecc.bls.g2_primitives import (
    G1_to_pubkey, G2_to_signature, pubkey_to_G1, signature_to_G2,
)
from py_ecc.bls import G2ProofOfPossession as bls_pop

# ── helpers ────────────────────────────────────────────────────────────────

def sha256(b: bytes) -> bytes:
    return hashlib.sha256(b).digest()

# Builder-deposit signing domain — distinct 4-byte domain type (0x0b000000,
# a placeholder pending consensus-specs allocation) with the same GENESIS
# fork-data suffix as the validator deposit domain. Must match
# DOMAIN_BUILDER_DEPOSIT in builder_deposit_contract.sol. Domain separation
# from the validator deposit domain (0x03000000…) prevents cross-context
# signature replay.
DOMAIN_BUILDER_DEPOSIT = bytes.fromhex(
    "0b000000f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a9"
)

def deposit_signing_root(pubkey: bytes, wc: bytes) -> bytes:
    """compute_signing_root for the 2-field builder message (pubkey, wc).

    The amount is intentionally NOT signed (see builder_deposit_contract.sol):
    htr = sha256(pubkey_root || wc); signing_root = sha256(htr || DOMAIN)."""
    assert len(pubkey) == 48 and len(wc) == 32
    pubkey_root = sha256(pubkey + b"\x00" * 16)
    msg_root = sha256(pubkey_root + wc)
    return sha256(msg_root + DOMAIN_BUILDER_DEPOSIT)

def split_fp(x: int) -> tuple:
    """Pack a 384-bit Fp value into the (hi:128, lo:256) form used by the verifier."""
    x %= Q
    return (x >> 256, x & ((1 << 256) - 1))

def sol_fp(x: int) -> str:
    hi, lo = split_fp(x)
    return f"BuilderDepositContract.Fp({hi:#034x}, {lo:#066x})"

def sol_fp2(a: int, b: int) -> str:
    return f"BuilderDepositContract.Fp2({sol_fp(a)}, {sol_fp(b)})"

def sol_hex_bytes(b: bytes) -> str:
    return 'hex"' + b.hex() + '"'

# ── end-to-end deposit signature ───────────────────────────────────────────

def deposit_test():
    # Deterministic private key for reproducibility (NOT a real key — purely
    # for round-tripping the verifier).
    sk = 0x4242424242424242424242424242424242424242424242424242424242424242
    pubkey = bls_pop.SkToPk(sk)
    wc = b"\x00" * 32
    amount = 32_000_000_000  # 32 ETH in gwei (credited stake; NOT signed)
    sr = deposit_signing_root(pubkey, wc)
    signature = bls_pop.Sign(sk, sr)
    assert bls_pop.Verify(pubkey, sr, signature), "py_ecc self-verify failed"

    pk_g1 = pubkey_to_G1(pubkey)
    sig_g2 = signature_to_G2(signature)
    pk_x, pk_y = normalize(pk_g1)
    sig_x, sig_y = normalize(sig_g2)

    # deposit_data_root: not consumed by BuilderDepositContract (it does not
    # take a deposit_data_root parameter), but included so that consensus-layer
    # log consumers can cross-check against the same SSZ structure used by
    # the validator deposit contract.
    pubkey_root = sha256(pubkey + b"\x00" * 16)
    sig_root = sha256(
        sha256(signature[:64]) + sha256(signature[64:] + b"\x00" * 32)
    )
    amount_bytes = amount.to_bytes(8, "little")
    node = sha256(
        sha256(pubkey_root + wc) + sha256(amount_bytes + b"\x00" * 24 + sig_root)
    )
    return {
        "pubkey": pubkey,
        "wc": wc,
        "amount_gwei": amount,
        "signature": signature,
        "deposit_data_root": node,
        "signing_root": sr,
        "pubkey_y_a": pk_y.n,
        "signature_y_a_a": sig_y.coeffs[0],
        "signature_y_a_b": sig_y.coeffs[1],
    }

# ── emit Solidity ──────────────────────────────────────────────────────────

def emit():
    out = []
    p = out.append

    p("// SPDX-License-Identifier: CC0-1.0")
    p("// AUTOGENERATED by gen_vectors.py — do not edit by hand.")
    p("//")
    p("// Cross-verification fixtures produced from py_ecc (the canonical Eth2")
    p("// Python reference implementation). Regenerate with:")
    p("//     /tmp/eipenv/bin/python gen_vectors.py > test/Vectors.sol")
    p("pragma solidity 0.6.11;")
    p("pragma experimental ABIEncoderV2;")
    p("")
    p('import "../builder_deposit_contract.sol";')
    p("")
    p("library Vectors {")
    p("")

    d = deposit_test()
    p("    // ── End-to-end deposit signature ──────────────────────────────────")
    p("    //")
    p("    // Generated from a deterministic secret key via")
    p("    // py_ecc.bls.G2ProofOfPossession (the Eth2 ciphersuite).")
    p("")
    p("    function depositCase() internal pure")
    p("        returns (")
    p("            bytes memory pubkey,")
    p("            bytes32 withdrawal_credentials,")
    p("            bytes memory signature,")
    p("            bytes32 deposit_data_root,")
    p("            uint64 amount_gwei,")
    p("            BuilderDepositContract.Fp memory pubkey_y,")
    p("            BuilderDepositContract.Fp2 memory signature_y")
    p("        )")
    p("    {")
    p(f"        pubkey = {sol_hex_bytes(d['pubkey'])};")
    p(f"        withdrawal_credentials = {'0x' + d['wc'].hex()};")
    p(f"        signature = {sol_hex_bytes(d['signature'])};")
    p(f"        deposit_data_root = {'0x' + d['deposit_data_root'].hex()};")
    p(f"        amount_gwei = {d['amount_gwei']};")
    p(f"        pubkey_y = {sol_fp(d['pubkey_y_a'])};")
    p(f"        signature_y = {sol_fp2(d['signature_y_a_a'], d['signature_y_a_b'])};")
    p("    }")
    p("")

    p("    /// @notice Expected `compute_signing_root` for `depositCase()`,")
    p("    /// computed in Python and baked in so the on-chain SSZ helper can be")
    p("    /// cross-checked without a second BLS pairing.")
    p("    function depositSigningRoot() internal pure returns (bytes32) {")
    p(f"        return {'0x' + d['signing_root'].hex()};")
    p("    }")
    p("")
    p("}")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    sys.stdout.write(emit())
