// SPDX-License-Identifier: CC0-1.0
// AUTOGENERATED by gen_vectors.py — do not edit by hand.
//
// Cross-verification fixtures produced from py_ecc (the canonical Eth2
// Python reference implementation). Regenerate with:
//     /tmp/eipenv/bin/python gen_vectors.py > test/Vectors.sol
pragma solidity 0.6.11;
pragma experimental ABIEncoderV2;

import "../builder_deposit_contract.sol";

library Vectors {

    // ── End-to-end deposit signature ──────────────────────────────────
    //
    // Generated from a deterministic secret key via
    // py_ecc.bls.G2ProofOfPossession (the Eth2 ciphersuite).

    function depositCase() internal pure
        returns (
            bytes memory pubkey,
            bytes32 withdrawal_credentials,
            bytes memory signature,
            bytes32 deposit_data_root,
            uint64 amount_gwei,
            BuilderDepositContract.Fp memory pubkey_y,
            BuilderDepositContract.Fp2 memory signature_y
        )
    {
        pubkey = hex"b5b99c967e4c69822f427db1f6871dd119afb95ab9646ba2e707990a3db31777a59b66f69e89c2055699b0ade7357eae";
        withdrawal_credentials = 0x0000000000000000000000000000000000000000000000000000000000000000;
        signature = hex"ab275ac905d68eb121c85caff35043de7e7bf478ec46b28a09eec700a4d2123572f18202f701d6a2974daddf7afba23b11199fa446bae3e67c630d45f62928dc3e3244317b485ff002e126e6b917ddcf4426f0903d68eb6743ab1a33fdaf56ed";
        deposit_data_root = 0xcf743a69594fad43bccf7056e08b2a3b12a6696d0a7ccf0527c48d6cabd98f01;
        amount_gwei = 32000000000;
        pubkey_y = BuilderDepositContract.Fp(0x1201d584a96bc82775861b0611171d2f, 0xfeaa2431c48856e23d3b747f7392fad645e0cdd5aa01b6a5b24b73ab584db4ad);
        signature_y = BuilderDepositContract.Fp2(BuilderDepositContract.Fp(0x12ca72b79300a13c051ed9170061f030, 0xf53694950c73fdb4f8130911d0dac6b13b423450cb333b467102fd22666d6593), BuilderDepositContract.Fp(0x14454e59e30d8480bc2bf6f3d08196f9, 0x285f86d269689bc843fcf8006d8b1448bfd6d71010aca7cba6ebde8b1154aa90));
    }

    /// @notice Expected `compute_signing_root` for `depositCase()`,
    /// computed in Python and baked in so the on-chain SSZ helper can be
    /// cross-checked without a second BLS pairing.
    function depositSigningRoot() internal pure returns (bytes32) {
        return 0xf764d63dcac69648e80ba943a88eaf62ce01a4c53998971787c3dc78b6f006c2;
    }

}
