[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10000
evm_version = "prague"
solc_version = "0.8.25"

[profile.lite]
optimizer = false
evm_version = "prague"
solc_version = "0.8.25"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
