"""Register intermediate code for validated EVM bytecode.

The deployable middle path.  Consensus clients are unlikely to JIT,
but validation makes translation linear-time and one-time, so a
client can translate validated code at deploy, cache the result, and
interpret *that*.  The IR spends the same proofs the AOT translator
spends — every destination constant, every slot at a static offset —
but keeps one dispatch per operation:

  * slots become numbered registers; POP vanishes; DUP is a move
  * PUSH fuses into the branch or call that consumes it
  * no destination checks, no per-op stack bookkeeping
  * gas is charged once per basic block, precomputed at translation
  * the checks validation cannot retire — stack overflow, return
    depth — cost one compare each per call, none per instruction

Registers are frame-relative: a call bumps the base by the caller's
retained items, so the callee's registers alias its arguments in
place, exactly the AOT translator's 256-bit frame discipline.

The IR instruction is four uint16 fields and one int64 immediate:
op, a (result / condition / k), b (operand / need), c (operand),
imm (constant / branch target / call target).  interp_ir.c executes
it at either width; ir_ops_h() generates the shared opcode numbering
so this file is the single source of truth.
"""
from aot import (annotate, INFO, TWIN_OF, size_of,
                 PUSH0, PUSH32, JUMP, JUMPI, JUMPDEST,
                 CALLSUB, CALLDEST, RETURNSUB, STOP, RETURN, REVERT)

OPS = ("GAS LI MV XCHG ADD SUB MUL DIV MOD LT GT SLT SGT EQ ISZERO "
       "AND OR XOR NOT SHL SHR CDLOAD CDSIZE MLOAD MSTORE "
       "J BNZ CALL RET RETURNDATA REVERT STOP").split()
OP = {name: i for i, name in enumerate(OPS)}

# EVM opcode -> IR op, for the arithmetic both widths share.
ALU = {0x01: "ADD", 0x03: "SUB", 0x02: "MUL", 0x04: "DIV", 0x06: "MOD",
       0x10: "LT", 0x11: "GT", 0x12: "SLT", 0x13: "SGT", 0x14: "EQ",
       0x15: "ISZERO", 0x16: "AND", 0x17: "OR", 0x18: "XOR",
       0x19: "NOT", 0x1B: "SHL", 0x1C: "SHR"}
UNARY = {0x15, 0x19}
DATA = {0x35: "CDLOAD", 0x51: "MLOAD", 0x52: "MSTORE",
        0xE0: "CDLOAD", 0xE1: "MLOAD", 0xE2: "MSTORE"}

# Gas per EVM opcode, as charged by the baseline interpreter: the
# block sums here and the per-op charges there must add up the same.
def evm_gas(op):
    return {0x02: 5, 0x04: 5, 0x06: 5, 0x36: 2, 0x50: 2, 0x5B: 1,
            0x5F: 2, 0x56: 8, 0x57: 10, 0xB0: 8, 0xB1: 1, 0xB2: 5,
            0xC2: 5, 0xC4: 5, 0xC6: 5}.get(op, 3)


def ir_ops_h():
    """The C side of the opcode numbering."""
    lines = ["/* generated by ir.py: do not edit */",
             "typedef struct { unsigned short op, a, b, c;"
             " long imm; } IR;"]
    for i, name in enumerate(OPS):
        lines.append(f"#define IR_{name} {i}")
    lines.append(f"#define IR_NOPS {len(OPS)}")
    return "\n".join(lines) + "\n"


class IRGen:
    def __init__(self, code):
        self.code = code
        self.n = annotate(code)
        self.out = []                 # [op, a, b, c, imm-or-("pc", evm_pc)]
        self.at_ir = {}               # evm pc -> ir index of its block/op

    def emit(self, op, a=0, b=0, c=0, imm=0):
        self.out.append([OP[op], a, b, c, imm])

    def generate(self):
        code, n = self.code, self.n
        pcs = sorted(n.offset)
        # Block leaders: entry, every destination and CALLDEST, and
        # every instruction following a control transfer.
        leaders = {0} | n.dests | {p for p in pcs if code[p] == CALLDEST}
        for pc in pcs:
            if code[pc] in (JUMP, JUMPI, CALLSUB, RETURNSUB):
                leaders.add(pc + size_of(code, pc))
        gas_at = None                 # ir index of the open block's GAS op
        for pc in pcs:
            op = code[pc]
            if pc in leaders:
                self.at_ir[pc] = len(self.out)
                self.emit("GAS")
                gas_at = len(self.out) - 1
            else:
                self.at_ir.setdefault(pc, len(self.out))
            self.out[gas_at][4] += evm_gas(op)
            if pc not in n.folded:
                self.instr(pc, op)
        # Patch branch and call targets from EVM pcs to IR indices.
        for ins in self.out:
            if isinstance(ins[4], tuple):
                ins[4] = self.at_ir[ins[4][1]]
        return self.out

    def instr(self, pc, op):
        n = self.n
        h = n.inputs[n.entry[pc]] + n.offset[pc]   # frame-relative top
        if PUSH0 <= op <= PUSH32:
            v = n.const[pc]
            assert v < 1 << 63, "push constant too wide for the IR"
            self.emit("LI", h, imm=v)
        elif 0x80 <= op <= 0x8F:
            self.emit("MV", h, h - (op - 0x7F))
        elif 0x90 <= op <= 0x9F:
            self.emit("XCHG", h - 1, h - 1 - (op - 0x8F))
        elif op in (0x50, JUMPDEST, CALLDEST):
            pass                       # gas already in the block sum
        elif op == 0x36:
            self.emit("CDSIZE", h)
        elif op in DATA:
            name = DATA[op]
            if name == "MSTORE":
                self.emit("MSTORE", h - 1, h - 2)
            else:
                self.emit(name, h - 1, h - 1)
        elif op in ALU or op in TWIN_OF:
            base = TWIN_OF.get(op, op)
            name = ALU[base]
            if base in UNARY:
                self.emit(name, h - 1, h - 1)
            else:                      # dest, top, next: in-place at next
                self.emit(name, h - 2, h - 1, h - 2)
        elif op == JUMP:
            self.emit("J", imm=("pc", self.dest(pc)))
        elif op == JUMPI:
            self.emit("BNZ", h - 2, imm=("pc", self.dest(pc)))
        elif op == CALLSUB:
            dest = n.callsite[pc]
            i = n.inputs[dest]
            k = h - 1 - i              # caller items kept below the args
            assert k >= 0, "call reaches below caller frame"
            need = i + n.maxh[dest]
            self.emit("CALL", k, need, imm=("pc", dest))
        elif op == RETURNSUB:
            self.emit("RET")
        elif op == RETURN:
            self.emit("RETURNDATA", h - 1, h - 2)
        elif op == REVERT:
            self.emit("REVERT")
        elif op == STOP:
            self.emit("STOP")
        else:
            raise NotImplementedError(f"opcode {op:#x} in the IR subset")

    def dest(self, pc):
        for back in range(1, 34):
            p = pc - back
            if p in self.n.const and p + size_of(self.code, p) == pc:
                return self.n.const[p]
        raise AssertionError("unfolded branch in valid code?")

    def to_c(self):
        rows = ",\n".join("    {%d, %d, %d, %d, %dL}" % tuple(i)
                          for i in self.generate())
        return ('#include "ir_ops.h"\n'
                f"const IR IRC[] = {{\n{rows}\n}};\n"
                f"const unsigned long IRC_LEN = "
                f"sizeof IRC / sizeof *IRC;\n")


def translate_ir(code):
    """Validated bytecode -> C source for the IR array."""
    return IRGen(code).to_c()
