on:
  pull_request_target:
  pull_request_review:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        type: string
        required: true
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Auto Review Bot Trigger
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Trigger
    steps:
      - name: Auto Review Bot
        uses: ethereum/eip-review-bot@dist
        continue-on-error: true
        if: >
          (github.event_name == 'pull_request_target' && ((!endsWith(github.event.sender.login, '-bot') && !endsWith(github.event.sender.login, '[bot]')) || github.event.sender.login == 'renovate[bot]')) ||
          (github.event_name == 'pull_request_review' && !endsWith(github.event.sender.login, '-bot') && !endsWith(github.event.sender.login, '[bot]')) ||
          (github.event_name == 'workflow_dispatch') ||
          (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@eth-bot rerun'))
        with:
          token: ${{ secrets.TOKEN }}
          config: config/eip-editors.yml
          pr_number: ${{ github.event_name == 'pull_request_target' && github.event.number || github.event_name == 'pull_request_review' && github.event.pull_request.number || github.event_name == 'workflow_dispatch' && inputs.pr_number || github.event_name == 'issue_comment' && github.event.issue.number || '' }}
