on:
  issue_comment:
    types:
      - created

name: Continuous Integration Re-Trigger
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Trigger
    steps:
      - name: Trigger
        uses: actions/github-script@v6
        if: github.event.issue.pull_request && contains(github.event.comment.body, '@eth-bot rerun')
        with:
          script: |
            let pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
              body: '[RETRIGGER]\n' + pr.data.body
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
              body: pr.data.body
            });
