on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

name: Post CI

permissions:
  actions: read
  contents: read
  pull-requests: write

# This is adapted from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run (2022-07-17)

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR Data
        id: fetch-pr-data
        uses: dawidd6/action-download-artifact@57aa996fc1713cc1579039614f4645a7f4841fd4 # v23
        with:
          name: pr_number
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: ignore

      - name: Save PR Data
        id: save-pr-data
        if: steps.fetch-pr-data.outputs.found_artifact == 'true'
        run: |
          set -euo pipefail
          for file in pr_number pr_sha merge_sha; do
            test -s "$file" || exit 0
          done
          {
            echo "pr_number=$(<pr_number)"
            echo "pr_sha=$(<pr_sha)"
            echo "merge_sha=$(<merge_sha)"
          } >> "$GITHUB_OUTPUT"

      - name: Add Comment
        uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443
        if: steps.save-pr-data.outputs.pr_number != '' && github.event.workflow_run.conclusion == 'failure'
        with:
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          recreate: true
          message: |
            The commit ${{ steps.save-pr-data.outputs.pr_sha }} (as a parent of ${{ steps.save-pr-data.outputs.merge_sha }}) contains errors.
            Please inspect the [Run Summary](https://github.com/ethereum/EIPs/pull/${{ steps.save-pr-data.outputs.pr_number }}/files) for details.

      - name: Add Waiting Label
        uses: actions-ecosystem/action-add-labels@288072f1a3b596f4350fe135bcfe381a23abadef
        if: steps.save-pr-data.outputs.pr_number != '' && github.event.workflow_run.conclusion == 'failure'
        with:
          labels: w-ci
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          repo: ${{ github.repository }}
          github_token: ${{ github.token }}

      - name: Remove Waiting Label
        uses: actions-ecosystem/action-remove-labels@d05162525702062b6bdef750ed8594fc024b3ed7
        if: steps.save-pr-data.outputs.pr_number != '' && github.event.workflow_run.conclusion != 'failure'
        with:
          labels: w-ci
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          repo: ${{ github.repository }}
          github_token: ${{ github.token }}
